title: Taylor Smith
baseurl: ""
url: "https://tsmith.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-environment-variables
exclude:
  - node_modules # Apparently this is magic sauce to make Jekyll less super slow
  - vendor # CircleCI stores Ruby gems inside the repo; skip this tree
  - assets # This is a symlink to _assets for JPT's links. Currently, Jekyll doesn't handle asset pipeline
  - bin
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - README.md
keep_files:
  - css   # Don't clobber site CSS, this way I don't have to store compiled CSS
  - js    # Don't clobber site JS, which is built with Gulp and includes Photoswipe
  - gfx   # Don't clobber site graphics/images/assets
  - assets # Don't clobber page/post assets; they're minimized with Gulp now
  - .htaccess
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png

# Site settings
permalink: /blog/:year/:slug/

# Collections / Content settings
defaults:
  - scope:
      type: projects
    values:
      layout: project
      photoswipe: true
  - scope:
      type: posts
    values:
      commenting: true
      layout: post
      highlighting: true
      photoswipe: true

collections:
  projects:
    output: true
    permalink: /project/:slug/

# Media handling
picture:
  source: "assets"
  # ^^ Because I'm having JPT link to all media assets in blog posts, the
  # "source" directory needed to be something that exists in the site build, so
  # I've symlinked repo/assets --> repo/_assets so that JPT can find the images
  # in the same path structure as the site build so links are also correct.
  # @TODO: This is stupid, brittle, and environmentally specific. Should I just
  # move _assets -> assets? Catch this in an output filter? Something else?
  output: "assets/generated"
  suppress_warnings: true
