baseURL = 'https://tsmith.com'
languageCode = 'en-us'
title = 'Taylor Smith'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
writeStats = true

[frontmatter]
  date = ':filename'

[permalinks]
  blog = '/blog/:year/:slug/'
  project = '/project/:slug/'

[markup.highlight]
  style = 'monokailight'
  tabWidth = 2

# I have a lot of static HTML from posts about experiments and I'm the only
# author, so I accept this -- unsafe just allows raw HTML.
[markup.goldmark.renderer]
  unsafe = true
