baseURL = 'https://tsmith.com/'
author = 'Taylor Smith'
languageCode = 'en-us'
title = 'Taylor Smith'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
writeStats = true

# Project archives are 2 or 3 columns, so bump this up from 10. Doesn't really
# matter on the blog.
paginate = 12

# Ten minutes
timeout = 600000

[params]
  description = 'Technical Product Manager'

[frontmatter]
  date = ['date', ':filename']

[permalinks]
  blog = '/blog/:year/:slug/'
  project = '/project/:slug/'

[markup.highlight]
  style = 'monokailight'
  tabWidth = 2

# I have a lot of static HTML from posts about experiments and I'm the only
# author, so I accept this -- unsafe just allows raw HTML.
[markup.goldmark.renderer]
  unsafe = true

[minify]
  minifyOutput = true
  [tdewolff.html]
    keepWhitespace = false

[outputs]
  home = ['HTML', 'RSS']
  page = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']

[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss'
    baseName = 'rss'

[services.rss]
  limit = 10
