title: Taylor Smith
baseurl: ""
url: "https://tsmith.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
keep_files:
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png

# Collections / Content settings
defaults:
  - scope:
      type: projects
    values:
      layout: project
      photoswipe: true

collections:
  projects:
    output: true
    permalink: /project/:slug/

# Media handling
picture:
  source: "assets"
  # ^^ Because I'm having JPT link to all media assets in blog posts, the
  # "source" directory needed to be something that exists in the site build, so
  # I've symlinked repo/assets --> repo/_assets so that JPT can find the images
  # in the same path structure as the site build so links are also correct.
  # @TODO: This is stupid, brittle, and environmentally specific. Should I just
  # move _assets -> assets? Catch this in an output filter? Something else?
  output: "assets/generated"
  suppress_warnings: true
