title: Taylor Smith
baseurl: ""
url: "https://tsmith.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
keep_files:
  - favicon.ico
  - favicon-16x16.png
  - favicon-32x32.png
